[settings]
  id = "5811be44-0095-4351-9776-65ba7447d70c"

[build]
  publish = "export/"

[[redirects]]
  from = "/*"
  to = "/articles/:splat"
  status = 301

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200